# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tNO56dfeMps5pCiFUTSMqKyr8n0_l5xK
"""

import matplotlib.pyplot as plt

import numpy as np

x = ["mario kart","pc man","wii fit","Pokémon Rojo/Verde/Azul/Amarillo","super mario bros","pug","wii sports","GTA V","tetris","minecraft"] 
y = [37,39,40,45,48,60,82,130,170,200]

plt.figure(figsize=(15,6))
plt.plot(x,y, marker='o',linestyle='--',color='r')
plt.xlabel("juegos")
plt.ylabel("ventas en total actualmente")
plt.title("top 10 de juegos mas vendidos en el mundo")
plt.xticks(x)
plt.show()