# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QVV9hjKVVn7mPYO7Fa_3aa11UTbLSTww
"""

import matplotlib.pyplot as plt

x = ['Argentina','Bolivia','Brasil','Chile','Colombia','Ecuador','Guayana Francesa','Guyana','Paraguay','Perú','Uruguay']
y = [2,0,5,0,0,0,0,0,0,0,2]

plt.figure(figsize=(20,6))
plt.title("copas mundiales")
plt.xlabel('Paises')
plt.ylabel("copas")
plt.bar(x,y)
plt.show()